name = "wisefile-fe"
compatibility_date = "2024-04-20"

[compatibility_flags]
nodejs_compat = true

[build]
command = "npm run build"

[site]
bucket = "./.svelte-kit/output/client"

[functions]
directory = ".svelte-kit/output/server"
